# cores: 1
# debug: True

cores: 128
jobs: 2

set-resources:
  get_methylc_and_coverage:
    cores: 64
    threads: 64
    mem_mb: 425000

use-apptainer: True
apptainer-prefix: workflow/rules/envs
software-deployment-method: apptainer
apptainer-args: -B /data

use-conda: True
conda-prefix: workflow/rules/envs
software-deployment-method: conda

rerun-incomplete: True
max-jobs-per-timespan: 1/1s
printshellcmds: True
retries: 3
