executor: local
jobs: unlimited

set-resources:
  indexing:
    threads: 52
    mem_mb: 500000
  mapping:
    threads: 26
    mem_mb: 250000
  get_coverage:
    threads: 13
    mem_mb: 125000
  generate_chrome_ctgs:
    threads: 13
    mem_mb: 125000
  calling:
    threads: 26
    mem_mb: 250000
  merge_chroms:
    threads: 26
    mem_mb: 250000
  gembs_extract:
    threads: 26
    mem_mb: 250000
  extract_signal:
    threads: 6
    mem_mb: 500000
  get_methylc:
    threads: 26
    mem_mb: 500000
  make_bedmethyl_pearson_correlation:
    threads: 52
    mem_mb: 500000

use-apptainer: True
apptainer-prefix: workflow/rules/envs
software-deployment-method: apptainer
apptainer-args: -B /data

rerun-incomplete: True
printshellcmds: True
keep-going: True
retries: 3
