# Pipeline configuration
workdir: "/data/zusers/ramirezc/wgbs-smk" # Required
metadata: "jobs/2026-01-17.failed/metadata.local.tsv" # Required
reference: "resources/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta.gz" # Required if make_index = True # Allow for gzip or non gzipped
assembly: "GRCh38" # Optional
species: "Homo_sapiens" # Optional (Assert no whitespace)
project: "MOHD"
tmpdir: "/tmp" # Required
make_index: True # Required
indexes_tar: "https://users.wenglab.org/ramirezc/indexes.tar.lz4" # Optional

index:
  sampling_rate: 4

mapping:
  non_stranded: false
  remove_individual_bams: true

calling:
  output_type: "b" # Enum (b, v, etc.) corresponding to output file types BCF, uncompressed BCF, VCF, etc.
  mapq_threshold: 10
  qual_threshold: 13
  reference_bias: 2
  left_trim: 5
  right_trim: 0
  keep_improper_pairs: false
  keep_duplicates: false
  haploid: false
  conversion: 0.01,0.05 # Must be a comma delimited string
  remove_individual_bcfs: true
  contig_pool_limit: 25000000

extract:
  strand_specific: true
  bw_strand_specific: true
  phred_threshold: 10
